const actions = {
  SET_USER: "user/SET_USER",
  LOGIN_STARTED: "user/LOGIN_STARTED",
  LOGIN_SUCCESS: "user/LOGIN_SUCCESS",
  LOGIN_FAILED: "user/LOGIN_FAILED",
  SIGNUP_STARTED: "user/SIGNUP_STARTED",
  SIGNUP_SUCCESS: "user/SIGNUP_SUCCESS",
  SIGNUP_FAILED: "user/SIGNUP_FAILED",
  LOGOUT_STARTED: "user/LOGOUT_STARTED",
  LOGOUT_SUCCESS: "user/LOGOUT_SUCCESS",
  LOGOUT_FAILED: "user/LOGOUT_FAILED",
};

export default actions;
