
name: Deploy New Version!

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.1.0'
      - run: npm i --package-lock-only
      - run: npm ci
      - run: CI=false && npm run build
      - name: Prod build triggered, deploying new version
        uses: w9jds/firebase-action@v1.5.0
        with:
          node-version: '14.18.0'
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
